version: "3.1"
services:
  db:
    build: ./containers/postgresql/
    image: keysoutsourcedocker/my_postgresql_build:9.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports: 
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - webnet
  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rest_api_test
      POSTGRES_PASSWORD: example
      POSTGRES_USER: rest_api_test
    ports:
      - "5434:5432"
    networks:
      - webnet
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    networks: 
      - webnet
  
  rest_api:
    image: keysoutsourcedocker/testjob:v1
    build: .
    ports: 
      - 80:3000
    networks: 
     - webnet
networks:
  webnet: